services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=gradebookdb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=erdem'
    ports:
      - '63070:5432'
    volumes:
      - './init.sql:docker-entrypoint-initdb.d/init.sql'